spring:
  application:
    name: kotkogram
  datasource:
    url: jdbc:postgresql://localhost:5432/kotkogram
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Kotkogram
          jwk-set-uri: http://localhost:8080/realms/Kotkogram/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: kotkogram-rest
      principle-attribute: preferred_username
